name: oam-fp
baseurl: /oam-fp
url:
description: Open Aid Map Front-page.
permalink: pretty
image:
github:

angular: 1.3.15

port: 4000
host: 127.0.0.1

exclude:
  - "*.lock"
  - "Gemfile"
  - ".scss-lint.yml"
  - "Rakefile"
  - ".travis.yml"

sass:
  style: :compressed
